# SITE CONFIGURATION
title: Amer's Blog # your site title
author: Geekgineer # You :P
description: > # Meta description of Homepage
  Abdalrahman M. Amer Blog I am a mission to demystify Intelligent Systems 
  topics such as Robotics, Self Driving Cars and Deep Learning
baseurl: "/amer" # the subpath of your site, e.g. /blog
url: "https://geekgineer.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
# social:
#   name: Your Name
#   links:
#     - https://twitter.com/BenBalter
#     - https://www.facebook.com/ben.balter
#     - https://www.linkedin.com/in/BenBalter
#     - https://plus.google.com/+BenBalter
#     - https://github.com/benbalter
#     - https://keybase.io/benbalter

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  On a mission to demystify Intelligent Systems topics such as Robotics, Self Driving Cars and Deep Learning

# Images tags
hero_img: posts/self-driving.jpeg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg
about_img: posts/about_cover_lg.jpeg
contact_img: posts/contact_me_lg.jpeg

# My email
email: abdalrahman.m5959@gmail.com # email for form submission

# Social Media handels
twitter_username: geekgineer # replace with your_twitter_username or comment to remove link from footer
github_username:  geekgineer # replace with your_github_username or comment to remove link from footer
instagram_username: geekgineer # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: geekgineer # to enable comments replace with your_disqus_shortname

google_tag_manager: GTM-5RMVDZF # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null

# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpeg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
